### Testando as rotas de Culture

# GET - Lista todas as cultures de uma fazenda específica
GET http://localhost:3000/farms/1/cultures
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyY3BmIjoiNDM0MyIsImlhdCI6MTczNzE0NTYzMSwiZXhwIjoxNzM3MTQ5MjMxfQ.c_kaQU2kilVrMl1kWG23D8ESgj-olGBdNxNKd4Vqe6k

###

# POST - Cria uma nova culture em uma fazenda
POST http://localhost:3000/farms/1/cultures
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyY3BmIjoiNDM0MyIsImlhdCI6MTczNzE0NTYzMSwiZXhwIjoxNzM3MTQ5MjMxfQ.c_kaQU2kilVrMl1kWG23D8ESgj-olGBdNxNKd4Vqe6k
Content-Type: application/json

{
  "local": "Campo Norte",
  "qtd": 50,
  "agricultureid": 3
}

###

# PUT - Atualiza uma culture específica
PUT http://localhost:3000/farms/1/cultures/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyY3BmIjoiNDM0MyIsImlhdCI6MTczNzE0NTYzMSwiZXhwIjoxNzM3MTQ5MjMxfQ.c_kaQU2kilVrMl1kWG23D8ESgj-olGBdNxNKd4Vqe6k
Content-Type: application/json

{
  "local": "Campo Sul",
  "qtd": 60,
  "agricultureid": 2
}

###

# DELETE - Deleta uma culture específica
DELETE http://localhost:3000/farms/1/cultures/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyY3BmIjoiNDM0MyIsImlhdCI6MTczNzE0NTYzMSwiZXhwIjoxNzM3MTQ5MjMxfQ.c_kaQU2kilVrMl1kWG23D8ESgj-olGBdNxNKd4Vqe6k

###

### Testando as rotas de Agriculture

# GET - Lista todas as agriculturas disponíveis
GET http://localhost:3000/agricultures
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyY3BmIjoiNDM0MyIsImlhdCI6MTczNzE0NTYzMSwiZXhwIjoxNzM3MTQ5MjMxfQ.c_kaQU2kilVrMl1kWG23D8ESgj-olGBdNxNKd4Vqe6k
Content-Type: application/json

###

# POST - Cria uma nova agricultura
POST http://localhost:3000/agricultures
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyY3BmIjoiNDM0MyIsImlhdCI6MTczNzE0NTYzMSwiZXhwIjoxNzM3MTQ5MjMxfQ.c_kaQU2kilVrMl1kWG23D8ESgj-olGBdNxNKd4Vqe6k
Content-Type: application/json

{
  "nome": "Milho",
  "valor_unid": 5,
  "neces_clima": "Tropical",
  "colhxanim": true,
  "needsId": [
    {
      "productId": 3,
      "qtd": 100
    },
    {
      "productId": 2,
      "qtd": 50
    }
  ] 
}

###

# PUT - Atualiza uma agricultura específica
PUT http://localhost:3000/agricultures/edit/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyY3BmIjoiNDM0MyIsImlhdCI6MTczNzE0NTYzMSwiZXhwIjoxNzM3MTQ5MjMxfQ.c_kaQU2kilVrMl1kWG23D8ESgj-olGBdNxNKd4Vqe6k
Content-Type: application/json

{
  "nome": "Soja",
  "valor_unid": 3,
  "neces_clima": "Outono" ,
  "colhxanim": true ,
  "needsId": [
    {
      "productId": 3,
      "qtd": 50
    }
  ]
}

###

# DELETE - Deleta uma agricultura específica
DELETE http://localhost:3000/agricultures/delete/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyY3BmIjoiNDM0MyIsImlhdCI6MTczNzE0NTYzMSwiZXhwIjoxNzM3MTQ5MjMxfQ.c_kaQU2kilVrMl1kWG23D8ESgj-olGBdNxNKd4Vqe6k


###

### Testando as rotas de Product

# GET - Lista todos os produtos
GET http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyY3BmIjoiNDM0MyIsImlhdCI6MTczNzE0NTYzMSwiZXhwIjoxNzM3MTQ5MjMxfQ.c_kaQU2kilVrMl1kWG23D8ESgj-olGBdNxNKd4Vqe6k
Content-Type: application/json

###

# POST - Cria um novo produto
POST http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyY3BmIjoiNDM0MyIsImlhdCI6MTczNzE0NTYzMSwiZXhwIjoxNzM3MTQ5MjMxfQ.c_kaQU2kilVrMl1kWG23D8ESgj-olGBdNxNKd4Vqe6k
Content-Type: application/json

{
  "nome": "Fertilizante X",
  "preco": 120.50
}

###

# PUT - Atualiza um produto específico
PUT http://localhost:3000/products/edit/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyY3BmIjoiNDM0MyIsImlhdCI6MTczNzE0NTYzMSwiZXhwIjoxNzM3MTQ5MjMxfQ.c_kaQU2kilVrMl1kWG23D8ESgj-olGBdNxNKd4Vqe6k
Content-Type: application/json

{
  "nome": "Fertilizante Premium",
  "preco": 150.00
}

###

# DELETE - Deleta um produto específico
DELETE http://localhost:3000/products/delete/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyY3BmIjoiNDM0MyIsImlhdCI6MTczNzE0NTYzMSwiZXhwIjoxNzM3MTQ5MjMxfQ.c_kaQU2kilVrMl1kWG23D8ESgj-olGBdNxNKd4Vqe6k
